/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersTableRouteImport } from './routes/users-table'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersTableAddUsersRouteImport } from './routes/users-table.add-users'

const RolesTableLazyRouteImport = createFileRoute('/roles-table')()
const CreateRolesLazyRouteImport = createFileRoute('/create-roles')()

const RolesTableLazyRoute = RolesTableLazyRouteImport.update({
  id: '/roles-table',
  path: '/roles-table',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/roles-table.lazy').then((d) => d.Route))
const CreateRolesLazyRoute = CreateRolesLazyRouteImport.update({
  id: '/create-roles',
  path: '/create-roles',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/create-roles.lazy').then((d) => d.Route))
const UsersTableRoute = UsersTableRouteImport.update({
  id: '/users-table',
  path: '/users-table',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersTableAddUsersRoute = UsersTableAddUsersRouteImport.update({
  id: '/add-users',
  path: '/add-users',
  getParentRoute: () => UsersTableRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/users-table': typeof UsersTableRouteWithChildren
  '/create-roles': typeof CreateRolesLazyRoute
  '/roles-table': typeof RolesTableLazyRoute
  '/users-table/add-users': typeof UsersTableAddUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/users-table': typeof UsersTableRouteWithChildren
  '/create-roles': typeof CreateRolesLazyRoute
  '/roles-table': typeof RolesTableLazyRoute
  '/users-table/add-users': typeof UsersTableAddUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/users-table': typeof UsersTableRouteWithChildren
  '/create-roles': typeof CreateRolesLazyRoute
  '/roles-table': typeof RolesTableLazyRoute
  '/users-table/add-users': typeof UsersTableAddUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/users-table'
    | '/create-roles'
    | '/roles-table'
    | '/users-table/add-users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/users-table'
    | '/create-roles'
    | '/roles-table'
    | '/users-table/add-users'
  id:
    | '__root__'
    | '/'
    | '/users-table'
    | '/create-roles'
    | '/roles-table'
    | '/users-table/add-users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsersTableRoute: typeof UsersTableRouteWithChildren
  CreateRolesLazyRoute: typeof CreateRolesLazyRoute
  RolesTableLazyRoute: typeof RolesTableLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roles-table': {
      id: '/roles-table'
      path: '/roles-table'
      fullPath: '/roles-table'
      preLoaderRoute: typeof RolesTableLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-roles': {
      id: '/create-roles'
      path: '/create-roles'
      fullPath: '/create-roles'
      preLoaderRoute: typeof CreateRolesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users-table': {
      id: '/users-table'
      path: '/users-table'
      fullPath: '/users-table'
      preLoaderRoute: typeof UsersTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users-table/add-users': {
      id: '/users-table/add-users'
      path: '/add-users'
      fullPath: '/users-table/add-users'
      preLoaderRoute: typeof UsersTableAddUsersRouteImport
      parentRoute: typeof UsersTableRoute
    }
  }
}

interface UsersTableRouteChildren {
  UsersTableAddUsersRoute: typeof UsersTableAddUsersRoute
}

const UsersTableRouteChildren: UsersTableRouteChildren = {
  UsersTableAddUsersRoute: UsersTableAddUsersRoute,
}

const UsersTableRouteWithChildren = UsersTableRoute._addFileChildren(
  UsersTableRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsersTableRoute: UsersTableRouteWithChildren,
  CreateRolesLazyRoute: CreateRolesLazyRoute,
  RolesTableLazyRoute: RolesTableLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
