/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersTableRouteImport } from './routes/users-table'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersTableAddUsersRouteImport } from './routes/users-table.add-users'
import { Route as RolesTableAddRolesRouteImport } from './routes/roles-table.add-roles'
import { Route as UsersTableUpdateUsersUserIdRouteImport } from './routes/users-table.update-users.$userId'

const RolesTableLazyRouteImport = createFileRoute('/roles-table')()

const RolesTableLazyRoute = RolesTableLazyRouteImport.update({
  id: '/roles-table',
  path: '/roles-table',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/roles-table.lazy').then((d) => d.Route))
const UsersTableRoute = UsersTableRouteImport.update({
  id: '/users-table',
  path: '/users-table',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersTableAddUsersRoute = UsersTableAddUsersRouteImport.update({
  id: '/add-users',
  path: '/add-users',
  getParentRoute: () => UsersTableRoute,
} as any)
const RolesTableAddRolesRoute = RolesTableAddRolesRouteImport.update({
  id: '/add-roles',
  path: '/add-roles',
  getParentRoute: () => RolesTableLazyRoute,
} as any)
const UsersTableUpdateUsersUserIdRoute =
  UsersTableUpdateUsersUserIdRouteImport.update({
    id: '/update-users/$userId',
    path: '/update-users/$userId',
    getParentRoute: () => UsersTableRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/users-table': typeof UsersTableRouteWithChildren
  '/roles-table': typeof RolesTableLazyRouteWithChildren
  '/roles-table/add-roles': typeof RolesTableAddRolesRoute
  '/users-table/add-users': typeof UsersTableAddUsersRoute
  '/users-table/update-users/$userId': typeof UsersTableUpdateUsersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/users-table': typeof UsersTableRouteWithChildren
  '/roles-table': typeof RolesTableLazyRouteWithChildren
  '/roles-table/add-roles': typeof RolesTableAddRolesRoute
  '/users-table/add-users': typeof UsersTableAddUsersRoute
  '/users-table/update-users/$userId': typeof UsersTableUpdateUsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/users-table': typeof UsersTableRouteWithChildren
  '/roles-table': typeof RolesTableLazyRouteWithChildren
  '/roles-table/add-roles': typeof RolesTableAddRolesRoute
  '/users-table/add-users': typeof UsersTableAddUsersRoute
  '/users-table/update-users/$userId': typeof UsersTableUpdateUsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/users-table'
    | '/roles-table'
    | '/roles-table/add-roles'
    | '/users-table/add-users'
    | '/users-table/update-users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/users-table'
    | '/roles-table'
    | '/roles-table/add-roles'
    | '/users-table/add-users'
    | '/users-table/update-users/$userId'
  id:
    | '__root__'
    | '/'
    | '/users-table'
    | '/roles-table'
    | '/roles-table/add-roles'
    | '/users-table/add-users'
    | '/users-table/update-users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsersTableRoute: typeof UsersTableRouteWithChildren
  RolesTableLazyRoute: typeof RolesTableLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roles-table': {
      id: '/roles-table'
      path: '/roles-table'
      fullPath: '/roles-table'
      preLoaderRoute: typeof RolesTableLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users-table': {
      id: '/users-table'
      path: '/users-table'
      fullPath: '/users-table'
      preLoaderRoute: typeof UsersTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users-table/add-users': {
      id: '/users-table/add-users'
      path: '/add-users'
      fullPath: '/users-table/add-users'
      preLoaderRoute: typeof UsersTableAddUsersRouteImport
      parentRoute: typeof UsersTableRoute
    }
    '/roles-table/add-roles': {
      id: '/roles-table/add-roles'
      path: '/add-roles'
      fullPath: '/roles-table/add-roles'
      preLoaderRoute: typeof RolesTableAddRolesRouteImport
      parentRoute: typeof RolesTableLazyRoute
    }
    '/users-table/update-users/$userId': {
      id: '/users-table/update-users/$userId'
      path: '/update-users/$userId'
      fullPath: '/users-table/update-users/$userId'
      preLoaderRoute: typeof UsersTableUpdateUsersUserIdRouteImport
      parentRoute: typeof UsersTableRoute
    }
  }
}

interface UsersTableRouteChildren {
  UsersTableAddUsersRoute: typeof UsersTableAddUsersRoute
  UsersTableUpdateUsersUserIdRoute: typeof UsersTableUpdateUsersUserIdRoute
}

const UsersTableRouteChildren: UsersTableRouteChildren = {
  UsersTableAddUsersRoute: UsersTableAddUsersRoute,
  UsersTableUpdateUsersUserIdRoute: UsersTableUpdateUsersUserIdRoute,
}

const UsersTableRouteWithChildren = UsersTableRoute._addFileChildren(
  UsersTableRouteChildren,
)

interface RolesTableLazyRouteChildren {
  RolesTableAddRolesRoute: typeof RolesTableAddRolesRoute
}

const RolesTableLazyRouteChildren: RolesTableLazyRouteChildren = {
  RolesTableAddRolesRoute: RolesTableAddRolesRoute,
}

const RolesTableLazyRouteWithChildren = RolesTableLazyRoute._addFileChildren(
  RolesTableLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsersTableRoute: UsersTableRouteWithChildren,
  RolesTableLazyRoute: RolesTableLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
